version: "3.8"

services:
  gitea:
    build:
      context: ./gitea
    image: k8s-lab/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - /opt/tools/gitea:/data

  nexus:
    build:
      context: ./nexus
    image: k8s-lab/nexus:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - /opt/tools/nexus/data:/nexus-data
